name: Cypress Tests CI

on:
  push:
    branches: [ "master" ]

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Build Docker image with Cypress included
      - name: Build Docker image
        run: docker build -t my-cypress-tests -f Dockerfile .

      # # Run tests inside the container
      # - name: Run Cypress tests
      #   run: docker run --rm my-cypress-tests

      # Run tests inside the container
      - name: Run Cypress tests
        run: |
          docker run --rm -v ${{ github.workspace }}/cypress/reports:/e2e/cypress/reports my-cypress-tests \ 
          cypress run --reporter cypress-mochawesome-reporter

      # Upload Mochawesome HTML reports as artifacts
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/reports/html

        
